export const CONTENT_BACKGROUND_EVENTS = {
  REMEMBER_THIS: "REMEMBER_THIS",
  REMEMBER_CONTENT: "REMEMBER_CONTENT",
  LET_REMEMBER: "LET_REMEMBER",
  CONTENT_EXTRACTED: "CONTENT_EXTRACTED",
  SELECTION_EXTRACTED: "SELECTION_EXTRACTED",
}