export const CONTENT_BACKGROUND_EVENTS = {
	REMEMBER_THIS: "REMEMBER_THIS",
	REMEMBER_CONTENT: "REMEMBER_CONTENT",
	LET_REMEMBER: "LET_REMEMBER",
	SHOW_TOPIC_SELECTOR: "SHOW_TOPIC_SELECTOR",
	CONTENT_EXTRACTED: "CONTENT_EXTRACTED",
	SELECTION_EXTRACTED: "SELECTION_EXTRACTED",
	RECALL: "RECALL",
	RECALL_TOPIC: "RECALL_TOPIC",
	SHOW_CHAT_MODAL: "SHOW_CHAT_MODAL",
	// PDF-specific events
	PDF_EXTRACT_PDF: "PDF_EXTRACT_PDF",
	PDF_EXTRACT_PDF_PAGES: "PDF_EXTRACT_PDF_PAGES",
	PDF_SEARCH_PDF: "PDF_SEARCH_PDF",
	PDF_EXPORT_PDF_TEXT: "PDF_EXPORT_PDF_TEXT",
	PDF_EXPORT_PDF_MARKDOWN: "PDF_EXPORT_PDF_MARKDOWN",
};
