import type { LLMModelConfig } from "../interfaces/llm-model-config";

const fp16KvBytesPerToken = (
	attentionLayers: number,
	keyValueHeads: number,
	headDimension: number,
) => 2 * attentionLayers * keyValueHeads * headDimension * 2;

export const TRANSFORMER_MODELS: LLMModelConfig[] = [
	{
		id: "onnx-community/LFM2.5-350M-ONNX",
		provider: "transformer",
		displayName: "LFM2.5 350M",
		sizeGB: 255148587 / 1024 ** 3,
		sizeLabel: "243MB",
		description: "⚡ LFM2.5 350M: newest Liquid tiny model, long context",
		contextLength: 128000,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(16, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 55,
		performanceScore: 96,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2026-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/functiongemma-270m-it-ONNX",
		provider: "transformer",
		displayName: "FunctionGemma 270M",
		sizeGB: 426243042 / 1024 ** 3,
		sizeLabel: "406MB",
		description: "🔧 FunctionGemma 270M: purpose-built for tool calling",
		contextLength: 32768,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(18, 1, 256),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 48,
		performanceScore: 97,
		contextScore: 85,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-12",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/granite-4.0-h-350m-ONNX",
		provider: "transformer",
		displayName: "Granite 4.0 H 350M",
		sizeGB: 238341600 / 1024 ** 3,
		sizeLabel: "227MB",
		description: "🪨 Granite 4.0 H 350M: IBM hybrid tiny model",
		contextLength: 32768,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(32, 4, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 60,
		performanceScore: 95,
		contextScore: 85,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Falcon-H1-Tiny-90M-Instruct-ONNX",
		provider: "transformer",
		displayName: "Falcon H1 Tiny 90M",
		sizeGB: 96721069 / 1024 ** 3,
		sizeLabel: "92MB",
		description: "🦅 Falcon H1 Tiny: smallest usable model, huge context",
		contextLength: 262144,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(24, 2, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 35,
		performanceScore: 99,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2026-01",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/LFM2-2.6B-ONNX",
		provider: "transformer",
		displayName: "LFM2 2.6B",
		sizeGB: 1655233726 / 1024 ** 3,
		sizeLabel: "1.54GB",
		description: "🌊 LFM2 2.6B: larger Liquid model with 128K context",
		contextLength: 128000,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(30, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 84,
		performanceScore: 68,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-09",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Qwen3-0.6B-Instruct-ONNX",
		provider: "transformer",
		displayName: "Qwen 3 0.6B Instruct",
		sizeGB: 648449396 / 1024 ** 3,
		sizeLabel: "618MB",
		description: "🐧 Qwen 3 0.6B Instruct: refreshed instruct tune",
		contextLength: 40960,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(28, 8, 128),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 73,
		performanceScore: 91,
		contextScore: 88,
		abilities: {
			tools: "prompt_injection",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2026-04",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/granite-4.0-micro-ONNX-web",
		provider: "transformer",
		displayName: "Granite 4.0 Micro",
		sizeGB: 2.3,
		sizeLabel: "2.3GB",
		description: "🪨 Granite 4.0 Micro: IBM browser-tuned WebGPU model",
		contextLength: 131072,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(40, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 5,
		qualityScore: 86,
		performanceScore: 82,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-05",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/granite-4.0-350m-ONNX-web",
		provider: "transformer",
		displayName: "Granite 4.0 350M",
		sizeGB: 350_484_597 / 1024 ** 3,
		sizeLabel: "334MB",
		description: "🪨 Granite 4.0 350M: compact browser-tuned instruct model",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(28, 4, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 58,
		performanceScore: 96,
		contextScore: 85,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-10",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/LFM2-1.2B-Tool-ONNX",
		provider: "transformer",
		displayName: "LFM2 1.2B Tool",
		sizeGB: 868_000_205 / 1024 ** 3,
		sizeLabel: "828MB",
		description: "🌊 LFM2 Tool: concise multilingual tool-calling specialist",
		contextLength: 128000,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 78,
		performanceScore: 82,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-09",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Qwen3-1.7B-ONNX",
		provider: "transformer",
		displayName: "Qwen 3 1.7B",
		sizeGB: 1_426_069_098 / 1024 ** 3,
		sizeLabel: "1.33GB",
		description: "🌐 Qwen 3 1.7B: balanced multilingual reasoning model",
		contextLength: 40960,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 114_688,
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 85,
		performanceScore: 80,
		contextScore: 88,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-04",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Qwen3-4B-ONNX",
		provider: "transformer",
		displayName: "Qwen 3 4B",
		sizeGB: 2_832_918_673 / 1024 ** 3,
		sizeLabel: "2.64GB",
		description: "🌐 Qwen 3 4B: higher-quality multilingual reasoning model",
		contextLength: 40960,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 147_456,
		requiresWebGPU: true,
		minMemoryGB: 6,
		qualityScore: 90,
		performanceScore: 66,
		contextScore: 88,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-04",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Llama-3.2-1B-Instruct-ONNX",
		provider: "transformer",
		displayName: "Llama 3.2 1B",
		sizeGB: 1_089_755_422 / 1024 ** 3,
		sizeLabel: "1.01GB",
		description: "🦙 Llama 3.2 1B: compact general-purpose instruct model",
		contextLength: 131072,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 32_768,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 68,
		performanceScore: 86,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2024-09",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Bonsai-1.7B-ONNX",
		provider: "transformer",
		displayName: "Bonsai 1.7B (Experimental)",
		sizeGB: 291_056_445 / 1024 ** 3,
		sizeLabel: "278MB",
		description: "🪴 Experimental 1-bit model optimized for tiny downloads",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 114_688,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 68,
		performanceScore: 94,
		contextScore: 85,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: false,
		},
		releaseDate: "2026-04",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q1",
		},
	},
	{
		id: "onnx-community/Apertus-v1.1-0.5B-Instruct-ONNX",
		provider: "transformer",
		displayName: "Apertus 1.1 0.5B (Experimental)",
		sizeGB: 517_345_436 / 1024 ** 3,
		sizeLabel: "493MB",
		description: "🇨🇭 Experimental fully open multilingual instruct model",
		contextLength: 4096,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: fp16KvBytesPerToken(20, 4, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 52,
		performanceScore: 94,
		contextScore: 50,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2026-07",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/Apertus-v1.1-1.5B-Instruct-ONNX",
		provider: "transformer",
		displayName: "Apertus 1.1 1.5B (Experimental)",
		sizeGB: 1_240_408_136 / 1024 ** 3,
		sizeLabel: "1.16GB",
		description: "🇨🇭 Experimental fully open multilingual instruct model",
		contextLength: 4096,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 32_768,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 70,
		performanceScore: 82,
		contextScore: 50,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2026-07",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/gemma-4-E2B-it-ONNX",
		provider: "transformer",
		displayName: "Gemma 4 E2B",
		sizeGB: 3_282_738_866 / 1024 ** 3,
		sizeLabel: "3.06GB",
		description: "💠 Gemma 4 E2B: Multimodal q4f16 WebGPU model",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(35, 1, 256),
		requiresWebGPU: true,
		minMemoryGB: 5,
		qualityScore: 87,
		performanceScore: 78,
		contextScore: 60,
		abilities: {
			tools: "native",
			vision: true,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-05",
		quickDownload: true,
		runnerConfig: {
			runtime: "image_text_to_text",
			dtype: "auto",
			postprocess: "gemma_clean",
			webgpuMaxContextTokens: 8192,
		},
	},
	{
		id: "LiquidAI/LFM2.5-1.2B-Thinking-ONNX",
		provider: "transformer",
		displayName: "LFM2.5 1.2B Thinking",
		sizeGB: 760_461_835 / 1024 ** 3,
		sizeLabel: "725MB",
		description: "🌊 LFM2.5 Thinking: Reasoning-focused q4 WebGPU model",
		contextLength: 128000,
		defaultMaxNewTokens: 4096,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 78,
		performanceScore: 84,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "text_generation_pipeline",
			dtype: "auto",
		},
	},
	{
		id: "LiquidAI/LFM2-8B-A1B-ONNX",
		provider: "transformer",
		displayName: "LFM2 8B-A1B",
		sizeGB: 4_784_501_794 / 1024 ** 3,
		sizeLabel: "4.46GB",
		description: "🌊 LFM2 8B-A1B: Mixture-of-experts q4f16 WebGPU model",
		contextLength: 128000,
		defaultMaxNewTokens: 4096,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 8,
		qualityScore: 88,
		performanceScore: 60,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "LiquidAI/LFM2-24B-A2B-ONNX",
		provider: "transformer",
		displayName: "LFM2 24B-A2B",
		sizeGB: 13_510_487_675 / 1024 ** 3,
		sizeLabel: "12.58GB",
		description: "🌊 LFM2 24B-A2B: Large mixture-of-experts q4f16 WebGPU model",
		contextLength: 128000,
		defaultMaxNewTokens: 4096,
		kvBytesPerToken: fp16KvBytesPerToken(10, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 16,
		qualityScore: 92,
		performanceScore: 45,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "HuggingFaceTB/SmolLM3-3B-ONNX",
		provider: "transformer",
		displayName: "SmolLM3 3B",
		sizeGB: 1.8,
		sizeLabel: "1.8GB",
		description: "🐭 SmolLM3 3B: Dual-mode reasoning, 64K context (WebGPU)",
		contextLength: 65536,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(36, 4, 128),
		requiresWebGPU: true,
		minMemoryGB: 5,
		qualityScore: 88,
		performanceScore: 82,
		contextScore: 92,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		// Instruct model, no-extended-thinking column, except gpqa which is the
		// extended-thinking figure and humaneval which is HumanEval+ on the base.
		qualityEvidence: {
			scores: {
				mmlu: 44.13,
				gpqa: 41.7,
				ifeval: 76.7,
				humaneval: 30.48,
				bfcl: 92.3,
			},
			source: "https://huggingface.co/HuggingFaceTB/SmolLM3-3B",
			recordedAt: "2026-08",
		},
		releaseDate: "2025-07",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/DeepSeek-R1-Distill-Qwen-1.5B-ONNX",
		provider: "transformer",
		displayName: "DeepSeek-R1 Qwen 1.5B",
		sizeGB: 1.5,
		sizeLabel: "1.5GB",
		description: "🧠 DeepSeek-R1: Reasoning specialist, 128K context (WebGPU)",
		contextLength: 131072,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 28_672,
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 85,
		performanceScore: 80,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-01",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Qwen3-0.6B-ONNX",
		provider: "transformer",
		displayName: "Qwen 3 0.6B",
		sizeGB: 0.4,
		sizeLabel: "400MB",
		description: "🌐 Qwen 3 0.6B: smallest, fastest, 40K context model",
		contextLength: 40960,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 114_688,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 70,
		performanceScore: 92,
		contextScore: 88,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-04",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Phi-4-mini-instruct-ONNX-GQA",
		provider: "transformer",
		displayName: "Phi 4 Mini",
		sizeGB: 3.1,
		sizeLabel: "3.1GB",
		description: "🔬 Phi 4: ONNX GQA WebGPU build for browser inference",
		contextLength: 131072,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(32, 8, 128),
		requiresWebGPU: true,
		minMemoryGB: 6,
		qualityScore: 89,
		performanceScore: 70,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-02",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/LFM2-350M-ONNX",
		provider: "transformer",
		displayName: "LFM2 350M",
		sizeGB: 255_148_587 / 1024 ** 3,
		sizeLabel: "243MB",
		description: "🌊 LFM2: Ultra-compact language model (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 40,
		performanceScore: 98,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/LFM2-700M-ONNX",
		provider: "transformer",
		displayName: "LFM2 700M",
		sizeGB: 496_287_466 / 1024 ** 3,
		sizeLabel: "473MB",
		description: "🌊 LFM2: Balanced performance model (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 60,
		performanceScore: 90,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/LFM2-1.2B-ONNX",
		provider: "transformer",
		displayName: "LFM2 1.2B",
		sizeGB: 760_462_148 / 1024 ** 3,
		sizeLabel: "725MB",
		description: "🌊 LFM2: High-quality model (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 75,
		performanceScore: 80,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "LiquidAI/LFM2.5-1.2B-Instruct-ONNX",
		provider: "transformer",
		displayName: "LFM2.5 1.2B Instruct",
		sizeGB: 760_461_835 / 1024 ** 3,
		sizeLabel: "725MB",
		description: "🌊 LFM2: specialist (WebGPU)",
		contextLength: 128000,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(6, 8, 64),
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 72,
		performanceScore: 82,
		contextScore: 98,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: true,
			multilingual: true,
		},
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "HuggingFaceTB/SmolLM2-135M-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 135M",
		sizeGB: 0.1,
		sizeLabel: "100MB",
		description: "SmolLM2 135M: ultra-light edge model",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(30, 3, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 30,
		performanceScore: 99,
		contextScore: 60,
		abilities: {
			tools: "prompt_injection",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2024-11",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "HuggingFaceTB/SmolLM2-360M-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 360M",
		sizeGB: 0.23,
		sizeLabel: "230MB",
		description: "🐭 SmolLM2: Efficient edge model (WebGPU)",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(32, 5, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 45,
		performanceScore: 96,
		contextScore: 60,
		abilities: {
			tools: "prompt_injection",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2024-11",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "HuggingFaceTB/SmolLM2-1.7B-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 1.7B",
		sizeGB: 1.0,
		sizeLabel: "1.0GB",
		description: "SmolLM2 1.7B: compact general-purpose chat model",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(24, 32, 64),
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 65,
		performanceScore: 83,
		contextScore: 60,
		abilities: {
			tools: "prompt_injection",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2024-11",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Qwen2.5-0.5B-Instruct",
		provider: "transformer",
		displayName: "Qwen 2.5 0.5B",
		sizeGB: 0.32,
		sizeLabel: "320MB",
		description: "🌐 Qwen2.5: Multilingual compact model (WebGPU)",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 12_288,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 55,
		performanceScore: 95,
		contextScore: 85,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2024-09",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Qwen2.5-1.5B-Instruct",
		provider: "transformer",
		displayName: "Qwen 2.5 1.5B",
		sizeGB: 0.9,
		sizeLabel: "900MB",
		description: "Qwen 2.5 1.5B: multilingual general chat model",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 28_672,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 72,
		performanceScore: 82,
		contextScore: 85,
		abilities: {
			tools: "native",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2024-09",
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "auto",
		},
	},
	{
		id: "onnx-community/Phi-4-mini-instruct",
		provider: "transformer",
		displayName: "Phi 4 Mini (Legacy ID)",
		sizeGB: 3.1,
		sizeLabel: "3.1GB",
		description:
			"Legacy Phi 4 browser ID kept only for unsupported-model messaging",
		contextLength: 131072,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(32, 8, 128),
		requiresWebGPU: true,
		minMemoryGB: 6,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		abilities: {
			tools: "none",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2025-02",
		unsupported: true,
		unsupportedReason:
			"onnx-community/Phi-4-mini-instruct does not expose the public browser-ready ONNX tokenizer files needed by this runtime. Use onnx-community/Phi-4-mini-instruct-ONNX-GQA instead.",
	},
	{
		id: "onnx-community/gemma-3-1b-it-ONNX",
		provider: "transformer",
		displayName: "Gemma 3 1B",
		sizeGB: 763_529_245 / 1024 ** 3,
		sizeLabel: "728MB",
		description: "💎 Gemma 3 1B: compact quality-focused instruct model",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 26_624,
		requiresWebGPU: true,
		minMemoryGB: 3,
		qualityScore: 78,
		performanceScore: 84,
		contextScore: 85,
		abilities: {
			tools: "prompt_injection",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/gemma-3-270m-it-ONNX",
		provider: "transformer",
		displayName: "Gemma 3 270M",
		sizeGB: 272_956_893 / 1024 ** 3,
		sizeLabel: "260MB",
		description: "💎 Gemma 3 270M: tiny instruct model for fast browser use",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 18_432,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 42,
		performanceScore: 96,
		contextScore: 85,
		abilities: {
			tools: "prompt_injection",
			vision: false,
			reasoning: false,
			multilingual: true,
		},
		releaseDate: "2025-03",
		quickDownload: true,
		runnerConfig: {
			runtime: "causal_lm",
			dtype: "q4f16",
		},
	},
	{
		id: "onnx-community/SmolLM2-135M-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 135M (Legacy ID)",
		sizeGB: 0.1,
		sizeLabel: "100MB",
		description: "Legacy inaccessible SmolLM2 model ID",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(30, 3, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		abilities: {
			tools: "none",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2024-11",
		unsupported: true,
		unsupportedReason:
			"This legacy repository is inaccessible. Select HuggingFaceTB/SmolLM2-135M-Instruct instead.",
	},
	{
		id: "onnx-community/SmolLM2-360M-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 360M (Legacy ID)",
		sizeGB: 0.23,
		sizeLabel: "230MB",
		description: "Legacy inaccessible SmolLM2 model ID",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(32, 5, 64),
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		abilities: {
			tools: "none",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2024-11",
		unsupported: true,
		unsupportedReason:
			"This legacy repository is inaccessible. Select HuggingFaceTB/SmolLM2-360M-Instruct instead.",
	},
	{
		id: "onnx-community/SmolLM2-1.7B-Instruct",
		provider: "transformer",
		displayName: "SmolLM2 1.7B (Legacy ID)",
		sizeGB: 1,
		sizeLabel: "1.0GB",
		description: "Legacy inaccessible SmolLM2 model ID",
		contextLength: 8192,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: fp16KvBytesPerToken(24, 32, 64),
		requiresWebGPU: true,
		minMemoryGB: 4,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		abilities: {
			tools: "none",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2024-11",
		unsupported: true,
		unsupportedReason:
			"This legacy repository is inaccessible. Select HuggingFaceTB/SmolLM2-1.7B-Instruct instead.",
	},
	{
		id: "onnx-community/gemma-3-270m-it",
		provider: "transformer",
		displayName: "Gemma 3 270M (Legacy ID)",
		sizeGB: 0.2,
		sizeLabel: "200MB",
		description: "Legacy Gemma 3 browser ID kept for compatibility",
		contextLength: 32768,
		defaultMaxNewTokens: 512,
		kvBytesPerToken: 18_432,
		requiresWebGPU: true,
		minMemoryGB: 2,
		qualityScore: 0,
		performanceScore: 0,
		contextScore: 0,
		abilities: {
			tools: "none",
			vision: false,
			reasoning: false,
			multilingual: false,
		},
		releaseDate: "2025-03",
		unsupported: true,
		unsupportedReason:
			"This repository does not exist. Select onnx-community/gemma-3-270m-it-ONNX instead.",
	},
];
