import type { LLMModelConfig } from "../interfaces/llm-model-config";

export const WLLAMA_MODELS: LLMModelConfig[] = [
	{
		id: "LiquidAI/LFM2-VL-450M-GGUF",
		provider: "wllama",
		displayName: "LFM2 VL 450M",
		sizeGB: 0.26,
		sizeLabel: "263MB",
		description: "Compact vision-language model",
		contextLength: 8192,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 8_192,
		requiresWebGPU: false,
		minMemoryGB: 2,
		qualityScore: 45,
		performanceScore: 75,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		wllamaConfig: {
			filename: "LFM2-VL-450M-Q4_0.gguf",
			mmprojFilename: "mmproj-LFM2-VL-450M-Q8_0.gguf",
		},
	},
	{
		id: "gabriellarson/LFM2-VL-450M-GGUF",
		provider: "wllama",
		displayName: "LFM2 VL 450M (Alt)",
		sizeGB: 0.26,
		sizeLabel: "263MB",
		description: "Alternate LFM2 VL 450M GGUF mirror",
		contextLength: 8192,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 8_192,
		requiresWebGPU: false,
		minMemoryGB: 2,
		qualityScore: 44,
		performanceScore: 74,
		contextScore: 60,
		releaseDate: "2024-11",
		wllamaConfig: {
			filename: "LFM2-VL-450M-Q4_0.gguf",
		},
	},
	{
		id: "LiquidAI/LFM2-VL-1.6B-GGUF",
		provider: "wllama",
		displayName: "LFM2 VL 1.6B",
		sizeGB: 0.95,
		sizeLabel: "952MB",
		description: "Advanced vision-language model",
		contextLength: 8192,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 24_576,
		requiresWebGPU: false,
		minMemoryGB: 3,
		qualityScore: 65,
		performanceScore: 62,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		wllamaConfig: {
			filename: "LFM2-VL-1.6B-Q4_0.gguf",
			mmprojFilename: "mmproj-LFM2-VL-1.6B-Q8_0.gguf",
		},
	},
	{
		id: "LiquidAI/LFM2-350M-GGUF",
		provider: "wllama",
		displayName: "LFM2 350M",
		sizeGB: 0.2,
		sizeLabel: "200MB",
		description: "LFM2 350M: ultra-compact CPU-friendly model",
		contextLength: 8192,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 8_192,
		requiresWebGPU: false,
		minMemoryGB: 2,
		qualityScore: 38,
		performanceScore: 78,
		contextScore: 60,
		releaseDate: "2024-11",
		wllamaConfig: {
			filename: "LFM2-350M-Q4_0.gguf",
		},
	},
	{
		id: "LiquidAI/LFM2-700M-GGUF",
		provider: "wllama",
		displayName: "LFM2 700M",
		sizeGB: 0.41,
		sizeLabel: "410MB",
		description: "Balanced performance model",
		contextLength: 8192,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 15_360,
		requiresWebGPU: false,
		minMemoryGB: 3,
		qualityScore: 60,
		performanceScore: 70,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		wllamaConfig: {
			filename: "LFM2-700M-Q4_0.gguf",
		},
	},
	{
		id: "LiquidAI/LFM2-1.2B-GGUF",
		provider: "wllama",
		displayName: "LFM2 1.2B",
		sizeGB: 0.71,
		sizeLabel: "709MB",
		description: "Large language model",
		contextLength: 8192,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 22_528,
		requiresWebGPU: false,
		minMemoryGB: 4,
		qualityScore: 75,
		performanceScore: 65,
		contextScore: 60,
		releaseDate: "2024-11",
		quickDownload: true,
		wllamaConfig: {
			filename: "LFM2-1.2B-Q4_0.gguf",
		},
	},
	{
		id: "ggml-org/SmolLM3-3B-GGUF",
		provider: "wllama",
		displayName: "SmolLM3 3B",
		sizeGB: 1.8,
		sizeLabel: "1.8GB",
		description: "SmolLM3 3B: long-context reasoning model for CPU fallback",
		contextLength: 128000,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 110_592,
		requiresWebGPU: false,
		minMemoryGB: 5,
		qualityScore: 88,
		performanceScore: 58,
		contextScore: 98,
		releaseDate: "2025-07",
		wllamaConfig: {
			filename: "SmolLM3-3B-Q4_K_M.gguf",
		},
	},
	{
		id: "ggml-org/Qwen3-1.7B-GGUF",
		provider: "wllama",
		displayName: "Qwen 3 1.7B",
		sizeGB: 1.1,
		sizeLabel: "1.1GB",
		description: "Qwen 3 1.7B: efficient CPU-friendly GGUF build",
		contextLength: 128000,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 114_688,
		requiresWebGPU: false,
		minMemoryGB: 4,
		qualityScore: 85,
		performanceScore: 60,
		contextScore: 98,
		releaseDate: "2025-04",
		wllamaConfig: {
			filename: "Qwen3-1.7B-Q4_K_M.gguf",
		},
	},
	{
		id: "unsloth/Qwen3-1.7B-GGUF",
		provider: "wllama",
		displayName: "Qwen 3 1.7B (Unsloth)",
		sizeGB: 1.1,
		sizeLabel: "1.1GB",
		description: "Alternate Qwen 3 1.7B GGUF build",
		contextLength: 128000,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 114_688,
		requiresWebGPU: false,
		minMemoryGB: 4,
		qualityScore: 84,
		performanceScore: 60,
		contextScore: 98,
		releaseDate: "2025-04",
		wllamaConfig: {
			filename: "Qwen3-1.7B-Q4_K_M.gguf",
		},
	},
	{
		id: "unsloth/Qwen3-0.6B-GGUF",
		provider: "wllama",
		displayName: "Qwen 3 0.6B",
		sizeGB: 0.45,
		sizeLabel: "450MB",
		description: "Qwen 3 0.6B: smallest GGUF variant for CPU use",
		contextLength: 32768,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 57_344,
		requiresWebGPU: false,
		minMemoryGB: 2,
		qualityScore: 68,
		performanceScore: 72,
		contextScore: 85,
		releaseDate: "2025-04",
		wllamaConfig: {
			filename: "Qwen3-0.6B-Q4_K_M.gguf",
		},
	},
	{
		id: "unsloth/Qwen3-4B-GGUF",
		provider: "wllama",
		displayName: "Qwen 3 4B",
		sizeGB: 2.4,
		sizeLabel: "2.4GB",
		description: "Qwen 3 4B: larger GGUF variant for stronger quality",
		contextLength: 128000,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 131_072,
		requiresWebGPU: false,
		minMemoryGB: 6,
		qualityScore: 90,
		performanceScore: 50,
		contextScore: 98,
		releaseDate: "2025-04",
		wllamaConfig: {
			filename: "Qwen3-4B-Q4_K_M.gguf",
		},
	},
	{
		id: "unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF",
		provider: "wllama",
		displayName: "DeepSeek-R1 Qwen 1.5B",
		sizeGB: 1.0,
		sizeLabel: "1.0GB",
		description: "DeepSeek-R1 distill for CPU/offline use",
		contextLength: 128000,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 28_672,
		requiresWebGPU: false,
		minMemoryGB: 3,
		qualityScore: 85,
		performanceScore: 65,
		contextScore: 98,
		releaseDate: "2025-01",
		wllamaConfig: {
			filename: "DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf",
		},
	},
	{
		id: "unsloth/gemma-3-1b-it-GGUF",
		provider: "wllama",
		displayName: "Gemma 3 1B",
		sizeGB: 0.72,
		sizeLabel: "722MB",
		description: "💎 Gemma 3 1B: Google's latest, 32K context",
		contextLength: 32768,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 16_384,
		requiresWebGPU: false,
		minMemoryGB: 3,
		qualityScore: 78,
		performanceScore: 68,
		contextScore: 85,
		releaseDate: "2025-03",
		quickDownload: true,
		wllamaConfig: {
			filename: "gemma-3-1b-it-Q4_0.gguf",
		},
	},
	{
		id: "unsloth/gemma-3-270m-it-GGUF",
		provider: "wllama",
		displayName: "Gemma 3 270M",
		sizeGB: 0.22,
		sizeLabel: "220MB",
		description: "Gemma 3 270M: tiny GGUF fallback for weak hardware",
		contextLength: 32768,
		defaultMaxNewTokens: 1024,
		kvBytesPerToken: 8_192,
		requiresWebGPU: false,
		minMemoryGB: 2,
		qualityScore: 42,
		performanceScore: 82,
		contextScore: 85,
		releaseDate: "2025-03",
		wllamaConfig: {
			filename: "gemma-3-270m-it-Q4_0.gguf",
		},
	},
	{
		id: "bartowski/Llama-3.2-1B-Instruct-GGUF",
		provider: "wllama",
		displayName: "Llama 3.2 1B",
		sizeGB: 0.8,
		sizeLabel: "800MB",
		description: "Llama 3.2 1B GGUF build for CPU-only use",
		contextLength: 131072,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 32_768,
		requiresWebGPU: false,
		minMemoryGB: 3,
		qualityScore: 64,
		performanceScore: 63,
		contextScore: 98,
		releaseDate: "2024-09",
		wllamaConfig: {
			filename: "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
		},
	},
	{
		id: "unsloth/Phi-4-mini-reasoning-GGUF",
		provider: "wllama",
		displayName: "Phi 4 Mini Reasoning",
		sizeGB: 3.1,
		sizeLabel: "3.1GB",
		description: "Phi 4 Mini reasoning-focused GGUF model",
		contextLength: 128000,
		defaultMaxNewTokens: 2048,
		kvBytesPerToken: 98_304,
		requiresWebGPU: false,
		minMemoryGB: 6,
		qualityScore: 89,
		performanceScore: 48,
		contextScore: 98,
		releaseDate: "2025-02",
		wllamaConfig: {
			filename: "Phi-4-mini-reasoning-Q4_K_M.gguf",
		},
	},
];
